// <auto-generated />
namespace BoatJourney.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTravelVesselRelatie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTravelVesselRelatie));
        
        string IMigrationMetadata.Id
        {
            get { return "201710092043249_AddTravelVesselRelatie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
